# Generated by Django 4.2.10 on 2025-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FontFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=10)),
                ('vector', models.TextField()),
            ],
            options={
                'unique_together': {('font_name', 'character')},
            },
        ),
    ]
